// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: drivers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDriver = `-- name: CreateDriver :one
INSERT INTO drivers (id, name, phone, license_no, vehicle_type, vehicle_no, rating, is_available, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, name, phone, license_no, vehicle_type, vehicle_no, rating, is_available, created_at, updated_at
`

type CreateDriverParams struct {
	ID          string           `json:"id"`
	Name        string           `json:"name"`
	Phone       string           `json:"phone"`
	LicenseNo   string           `json:"license_no"`
	VehicleType string           `json:"vehicle_type"`
	VehicleNo   string           `json:"vehicle_no"`
	Rating      pgtype.Numeric   `json:"rating"`
	IsAvailable *bool            `json:"is_available"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateDriver(ctx context.Context, arg CreateDriverParams) (Driver, error) {
	row := q.db.QueryRow(ctx, createDriver,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.LicenseNo,
		arg.VehicleType,
		arg.VehicleNo,
		arg.Rating,
		arg.IsAvailable,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.LicenseNo,
		&i.VehicleType,
		&i.VehicleNo,
		&i.Rating,
		&i.IsAvailable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDriver = `-- name: DeleteDriver :exec
DELETE FROM drivers WHERE id = $1
`

func (q *Queries) DeleteDriver(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteDriver, id)
	return err
}

const getDriver = `-- name: GetDriver :one
SELECT id, name, phone, license_no, vehicle_type, vehicle_no, rating, is_available, created_at, updated_at FROM drivers WHERE id = $1
`

func (q *Queries) GetDriver(ctx context.Context, id string) (Driver, error) {
	row := q.db.QueryRow(ctx, getDriver, id)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.LicenseNo,
		&i.VehicleType,
		&i.VehicleNo,
		&i.Rating,
		&i.IsAvailable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAvailableDrivers = `-- name: ListAvailableDrivers :many
SELECT id, name, phone, license_no, vehicle_type, vehicle_no, rating, is_available, created_at, updated_at FROM drivers WHERE is_available = true
`

func (q *Queries) ListAvailableDrivers(ctx context.Context) ([]Driver, error) {
	rows, err := q.db.Query(ctx, listAvailableDrivers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Driver{}
	for rows.Next() {
		var i Driver
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.LicenseNo,
			&i.VehicleType,
			&i.VehicleNo,
			&i.Rating,
			&i.IsAvailable,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDriverAvailability = `-- name: UpdateDriverAvailability :exec
UPDATE drivers SET is_available = $2, updated_at = $3 WHERE id = $1
`

type UpdateDriverAvailabilityParams struct {
	ID          string           `json:"id"`
	IsAvailable *bool            `json:"is_available"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateDriverAvailability(ctx context.Context, arg UpdateDriverAvailabilityParams) error {
	_, err := q.db.Exec(ctx, updateDriverAvailability, arg.ID, arg.IsAvailable, arg.UpdatedAt)
	return err
}

const updateDriverRating = `-- name: UpdateDriverRating :exec
UPDATE drivers SET rating = $2, updated_at = $3 WHERE id = $1
`

type UpdateDriverRatingParams struct {
	ID        string           `json:"id"`
	Rating    pgtype.Numeric   `json:"rating"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateDriverRating(ctx context.Context, arg UpdateDriverRatingParams) error {
	_, err := q.db.Exec(ctx, updateDriverRating, arg.ID, arg.Rating, arg.UpdatedAt)
	return err
}
