// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Driver struct {
	ID          string           `json:"id"`
	Name        string           `json:"name"`
	Phone       string           `json:"phone"`
	LicenseNo   string           `json:"license_no"`
	VehicleType string           `json:"vehicle_type"`
	VehicleNo   string           `json:"vehicle_no"`
	Rating      pgtype.Numeric   `json:"rating"`
	IsAvailable *bool            `json:"is_available"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Payment struct {
	ID            string           `json:"id"`
	UserID        string           `json:"user_id"`
	TravelID      string           `json:"travel_id"`
	Amount        pgtype.Numeric   `json:"amount"`
	Status        string           `json:"status"`
	PaymentMethod string           `json:"payment_method"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type Place struct {
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	Address   string           `json:"address"`
	Latitude  pgtype.Numeric   `json:"latitude"`
	Longitude pgtype.Numeric   `json:"longitude"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type TravelHistory struct {
	ID         string           `json:"id"`
	UserID     string           `json:"user_id"`
	DriverID   string           `json:"driver_id"`
	PickupLoc  string           `json:"pickup_loc"`
	DropoffLoc string           `json:"dropoff_loc"`
	Distance   pgtype.Numeric   `json:"distance"`
	Fare       pgtype.Numeric   `json:"fare"`
	Status     string           `json:"status"`
	StartTime  pgtype.Timestamp `json:"start_time"`
	EndTime    pgtype.Timestamp `json:"end_time"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Phone    string `json:"phone"`
}
