// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: payments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (id, user_id, travel_id, amount, status, payment_method, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, travel_id, amount, status, payment_method, created_at
`

type CreatePaymentParams struct {
	ID            string           `json:"id"`
	UserID        string           `json:"user_id"`
	TravelID      string           `json:"travel_id"`
	Amount        pgtype.Numeric   `json:"amount"`
	Status        string           `json:"status"`
	PaymentMethod string           `json:"payment_method"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.ID,
		arg.UserID,
		arg.TravelID,
		arg.Amount,
		arg.Status,
		arg.PaymentMethod,
		arg.CreatedAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TravelID,
		&i.Amount,
		&i.Status,
		&i.PaymentMethod,
		&i.CreatedAt,
	)
	return i, err
}

const deletePayment = `-- name: DeletePayment :exec
DELETE FROM payments WHERE id = $1
`

func (q *Queries) DeletePayment(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePayment, id)
	return err
}

const getPayment = `-- name: GetPayment :one
SELECT id, user_id, travel_id, amount, status, payment_method, created_at FROM payments WHERE id = $1
`

func (q *Queries) GetPayment(ctx context.Context, id string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TravelID,
		&i.Amount,
		&i.Status,
		&i.PaymentMethod,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentByTravelID = `-- name: GetPaymentByTravelID :one
SELECT id, user_id, travel_id, amount, status, payment_method, created_at FROM payments WHERE travel_id = $1
`

func (q *Queries) GetPaymentByTravelID(ctx context.Context, travelID string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByTravelID, travelID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TravelID,
		&i.Amount,
		&i.Status,
		&i.PaymentMethod,
		&i.CreatedAt,
	)
	return i, err
}

const listUserPayments = `-- name: ListUserPayments :many
SELECT id, user_id, travel_id, amount, status, payment_method, created_at FROM payments WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListUserPayments(ctx context.Context, userID string) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listUserPayments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TravelID,
			&i.Amount,
			&i.Status,
			&i.PaymentMethod,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE payments SET status = $2 WHERE id = $1
`

type UpdatePaymentStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.Exec(ctx, updatePaymentStatus, arg.ID, arg.Status)
	return err
}
