// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: places.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlace = `-- name: CreatePlace :one
INSERT INTO places (id, name, address, latitude, longitude, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, address, latitude, longitude, created_at
`

type CreatePlaceParams struct {
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	Address   string           `json:"address"`
	Latitude  pgtype.Numeric   `json:"latitude"`
	Longitude pgtype.Numeric   `json:"longitude"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreatePlace(ctx context.Context, arg CreatePlaceParams) (Place, error) {
	row := q.db.QueryRow(ctx, createPlace,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.CreatedAt,
	)
	var i Place
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
	)
	return i, err
}

const deletePlace = `-- name: DeletePlace :exec
DELETE FROM places WHERE id = $1
`

func (q *Queries) DeletePlace(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePlace, id)
	return err
}

const getPlace = `-- name: GetPlace :one
SELECT id, name, address, latitude, longitude, created_at FROM places WHERE id = $1
`

func (q *Queries) GetPlace(ctx context.Context, id string) (Place, error) {
	row := q.db.QueryRow(ctx, getPlace, id)
	var i Place
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
	)
	return i, err
}

const listPlaces = `-- name: ListPlaces :many
SELECT id, name, address, latitude, longitude, created_at FROM places ORDER BY name
`

func (q *Queries) ListPlaces(ctx context.Context) ([]Place, error) {
	rows, err := q.db.Query(ctx, listPlaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Place{}
	for rows.Next() {
		var i Place
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
