// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateDriver(ctx context.Context, arg CreateDriverParams) (Driver, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreatePlace(ctx context.Context, arg CreatePlaceParams) (Place, error)
	CreateTravelHistory(ctx context.Context, arg CreateTravelHistoryParams) (TravelHistory, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteDriver(ctx context.Context, id string) error
	DeletePayment(ctx context.Context, id string) error
	DeletePlace(ctx context.Context, id string) error
	DeleteTravelHistory(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	GetDriver(ctx context.Context, id string) (Driver, error)
	GetPayment(ctx context.Context, id string) (Payment, error)
	GetPaymentByTravelID(ctx context.Context, travelID string) (Payment, error)
	GetPlace(ctx context.Context, id string) (Place, error)
	GetTravelHistory(ctx context.Context, id string) (TravelHistory, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	ListAvailableDrivers(ctx context.Context) ([]Driver, error)
	ListDriverTravelHistory(ctx context.Context, driverID string) ([]TravelHistory, error)
	ListPlaces(ctx context.Context) ([]Place, error)
	ListUserPayments(ctx context.Context, userID string) ([]Payment, error)
	ListUserTravelHistory(ctx context.Context, userID string) ([]TravelHistory, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateDriverAvailability(ctx context.Context, arg UpdateDriverAvailabilityParams) error
	UpdateDriverRating(ctx context.Context, arg UpdateDriverRatingParams) error
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error
	UpdateTravelStatus(ctx context.Context, arg UpdateTravelStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
