// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: travel_histories.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTravelHistory = `-- name: CreateTravelHistory :one
INSERT INTO travel_histories (id, user_id, driver_id, pickup_loc, dropoff_loc, distance, fare, status, start_time, end_time, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, driver_id, pickup_loc, dropoff_loc, distance, fare, status, start_time, end_time, created_at
`

type CreateTravelHistoryParams struct {
	ID         string           `json:"id"`
	UserID     string           `json:"user_id"`
	DriverID   string           `json:"driver_id"`
	PickupLoc  string           `json:"pickup_loc"`
	DropoffLoc string           `json:"dropoff_loc"`
	Distance   pgtype.Numeric   `json:"distance"`
	Fare       pgtype.Numeric   `json:"fare"`
	Status     string           `json:"status"`
	StartTime  pgtype.Timestamp `json:"start_time"`
	EndTime    pgtype.Timestamp `json:"end_time"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateTravelHistory(ctx context.Context, arg CreateTravelHistoryParams) (TravelHistory, error) {
	row := q.db.QueryRow(ctx, createTravelHistory,
		arg.ID,
		arg.UserID,
		arg.DriverID,
		arg.PickupLoc,
		arg.DropoffLoc,
		arg.Distance,
		arg.Fare,
		arg.Status,
		arg.StartTime,
		arg.EndTime,
		arg.CreatedAt,
	)
	var i TravelHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DriverID,
		&i.PickupLoc,
		&i.DropoffLoc,
		&i.Distance,
		&i.Fare,
		&i.Status,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTravelHistory = `-- name: DeleteTravelHistory :exec
DELETE FROM travel_histories WHERE id = $1
`

func (q *Queries) DeleteTravelHistory(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTravelHistory, id)
	return err
}

const getTravelHistory = `-- name: GetTravelHistory :one
SELECT id, user_id, driver_id, pickup_loc, dropoff_loc, distance, fare, status, start_time, end_time, created_at FROM travel_histories WHERE id = $1
`

func (q *Queries) GetTravelHistory(ctx context.Context, id string) (TravelHistory, error) {
	row := q.db.QueryRow(ctx, getTravelHistory, id)
	var i TravelHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DriverID,
		&i.PickupLoc,
		&i.DropoffLoc,
		&i.Distance,
		&i.Fare,
		&i.Status,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
	)
	return i, err
}

const listDriverTravelHistory = `-- name: ListDriverTravelHistory :many
SELECT id, user_id, driver_id, pickup_loc, dropoff_loc, distance, fare, status, start_time, end_time, created_at FROM travel_histories WHERE driver_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDriverTravelHistory(ctx context.Context, driverID string) ([]TravelHistory, error) {
	rows, err := q.db.Query(ctx, listDriverTravelHistory, driverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TravelHistory{}
	for rows.Next() {
		var i TravelHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DriverID,
			&i.PickupLoc,
			&i.DropoffLoc,
			&i.Distance,
			&i.Fare,
			&i.Status,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTravelHistory = `-- name: ListUserTravelHistory :many
SELECT id, user_id, driver_id, pickup_loc, dropoff_loc, distance, fare, status, start_time, end_time, created_at FROM travel_histories WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListUserTravelHistory(ctx context.Context, userID string) ([]TravelHistory, error) {
	rows, err := q.db.Query(ctx, listUserTravelHistory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TravelHistory{}
	for rows.Next() {
		var i TravelHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DriverID,
			&i.PickupLoc,
			&i.DropoffLoc,
			&i.Distance,
			&i.Fare,
			&i.Status,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTravelStatus = `-- name: UpdateTravelStatus :exec
UPDATE travel_histories SET status = $2, end_time = $3 WHERE id = $1
`

type UpdateTravelStatusParams struct {
	ID      string           `json:"id"`
	Status  string           `json:"status"`
	EndTime pgtype.Timestamp `json:"end_time"`
}

func (q *Queries) UpdateTravelStatus(ctx context.Context, arg UpdateTravelStatusParams) error {
	_, err := q.db.Exec(ctx, updateTravelStatus, arg.ID, arg.Status, arg.EndTime)
	return err
}
